services:
  web: 
    build:
      context: app
      target: builder
    image: atvfool/sensorlogging
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '8000:8000'
    volumes:
      - app:/app
volumes:
  app:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'